version: "3.1"

services:
  api:
    container_name: tictocApp
    image: node:11
    restart: always
    volumes:
      - ./src:/var/www/src
      - ./node_modules:/var/www/node_modules
      - ./package.json:/var/www/package.json
      - ./nodemon.json:/var/www/nodemon.json
      - ./tsconfig.json:/var/www/tsconfig.json
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    command: --init-file /data/application/setup.sql
    volumes:
      - ./setup.sql:/data/application/setup.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tictocDb
    ports:
      - "3306:3306"
